// Generated by Selenium IDE
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import java.time.Duration;

public class BlazeDemoTest {
  private WebDriver driver;
  JavascriptExecutor js;


  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }

  @Test
  public void buyFlightBooking() {

    driver.get("https://blazedemo.com/");
    driver.manage().window().setSize(new Dimension(945, 1011));

    driver.findElement(By.cssSelector(".btn-primary")).click();

    ChromeOptions options = new ChromeOptions();
    options.setBinary("/snap/bin/chromium");
    options.addArguments("--disable-features=BackForwardCache");
    driver = new ChromeDriver(options);

    driver.findElement(By.id("inputName")).click();
    driver.findElement(By.id("nameOnCard")).sendKeys("weofinief");

    driver.findElement(By.cssSelector(".btn-primary")).click();

    assertThat(driver.getTitle()).contains("confirmation");
    driver.close();
  }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }
}
