name: Java CI

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Set up JDK 23
        uses: actions/setup-java@v2  
        with:
          java-version: '23'  
          distribution: 'temurin'  

      - name: Run unit tests
        run: |
          cd HW1/meal-booking-backend  
          sudo mvn clean test
      - name: Run Functional tests
        run: |
          cd HW1/meal-booking-backend  
          sudo mvn -Dtest=CucumberTest test
      - name: Run integration tests
        run: |
          cd HW1/meal-booking-backend
          sudo mvn clean failsafe:integration-test verify
