name: Java CI

on:
  push:
    branches:
      - master 

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'  
          distribution: 'temurin'  
          cache: 'maven'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

  unit-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Run unit tests
        run: |
          cd HW1/meal-booking-backend  
          mvn clean test

  integration-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Run integration tests
        run: |
          cd HW1/meal-booking-backend
          mvn test -Dtest=**/*IT.java