name: Java CI

on:
  push:
    branches:
      - master  # Triggers the workflow on pushes to the master branch


jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the repository code

      - name: Set up JDK 23
        uses: actions/setup-java@v2  # Use the correct version of the action
        with:
          java-version: '23'  # Specify the Java version you want to use
          distribution: 'temurin'  # Specify the distribution (e.g., 'temurin', 'adopt', etc.)

      - name: Build with Maven
        run: |
          cd HW1/meal-booking-backend  
          mvn clean test

#      - name: Run integration tests
#        run: |
#          cd HW1/meal-booking-backend 
#          mvn -B verify failsafe:integration-test

#      - name: Run controllers tests
#        run: |
#          cd HW1/meal-booking-backend 
#          sudo mvn clean test -Dtest=controllers.*Test

